name: Docker Build and Run Check

on:
  pull_request:

  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get the repository name in lowercase
        id: repo_name
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')
          echo ::set-output name=REPO_NAME::$REPO_NAME

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          load: true
          tags: ${{ steps.repo_name.outputs.REPO_NAME }}:pr-test

      - name: Run Docker container
        run: |
          docker run --name test-container -d ${{ steps.repo_name.outputs.REPO_NAME }}:pr-test
          sleep 10
          if [[ "$(docker ps -q -f name=test-container)" ]]; then
            echo "Container is running."
          else
            echo "Container is not running."
            exit 1
          fi
