name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    steps:
      - name: Check if the push event has a semantic version tag
        id: check
        run: |
          if [[ $GITHUB_REF =~ refs/tags/[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "::set-output name=proceed::true"
          else
            echo "::set-output name=proceed::false"
          fi

  build:
    needs: check
    if: needs.check.outputs.proceed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo ::set-output name=VERSION::$VERSION

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angular-realworld-example-app:${{ steps.get_version.outputs.VERSION }}
